include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Reglas para forzar el uso de 'const' cuando es posible
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables